Integrate mima into the build.
Not that I'm offering binary compatibility to anything
here on day two, but that day will come. The test can be run
with 'sbt mima'. Presently it tells us, comparing against the
initial release 0.1.0-M1, that:

% sbt mima
[info] psp-std: found 13 potential binary incompatibilities
[error]  * method x()java.lang.Object in class psp.std.AnyExtensionOps does not have a correspondent in new version
[error]    filter with: ProblemFilters.exclude[MissingMethodProblem]("psp.std.AnyExtensionOps.x")
[error]  * method indexRange(Int,Int)Long in trait psp.std.Creators does not have a correspondent in old version
[error]    filter with: ProblemFilters.exclude[MissingMethodProblem]("psp.std.Creators.indexRange")
[error]  * method x()scala.util.Try in class psp.std.TryExtensionOps does not have a correspondent in new version
[error]    filter with: ProblemFilters.exclude[MissingMethodProblem]("psp.std.TryExtensionOps.x")
[error]  * method stringExtensionOps(java.lang.String)java.lang.String in trait psp.std.Implicits does not have a correspondent in new version
[error]    filter with: ProblemFilters.exclude[MissingMethodProblem]("psp.std.Implicits.stringExtensionOps")
[error]  * method pspAugmentString(java.lang.String)java.lang.String in trait psp.std.Implicits does not have a correspondent in old version
[error]    filter with: ProblemFilters.exclude[MissingMethodProblem]("psp.std.Implicits.pspAugmentString")
[error]  * method pspUnaugmentString(java.lang.String)java.lang.String in trait psp.std.Implicits does not have a correspondent in old version
[error]    filter with: ProblemFilters.exclude[MissingMethodProblem]("psp.std.Implicits.pspUnaugmentString")
[error]  * method stringExtensionOps(java.lang.String)java.lang.String in object psp.std.package does not have a correspondent in new version
[error]    filter with: ProblemFilters.exclude[MissingMethodProblem]("psp.std.package.stringExtensionOps")
[error]  * method unaugmentString()scala.runtime.Null# in trait psp.std.ImplicitRemoval does not have a correspondent in old version
[error]    filter with: ProblemFilters.exclude[MissingMethodProblem]("psp.std.ImplicitRemoval.unaugmentString")
[error]  * synthetic method psp$std$ImplicitRemoval$_setter_$augmentString_=(scala.runtime.Null#)Unit in trait psp.std.ImplicitRemoval does not have a correspondent in old version
[error]    filter with: ProblemFilters.exclude[MissingMethodProblem]("psp.std.ImplicitRemoval.psp$std$ImplicitRemoval$_setter_$augmentString_=")
[error]  * method augmentString()scala.runtime.Null# in trait psp.std.ImplicitRemoval does not have a correspondent in old version
[error]    filter with: ProblemFilters.exclude[MissingMethodProblem]("psp.std.ImplicitRemoval.augmentString")
[error]  * synthetic method psp$std$ImplicitRemoval$_setter_$unaugmentString_=(scala.runtime.Null#)Unit in trait psp.std.ImplicitRemoval does not have a correspondent in old version
[error]    filter with: ProblemFilters.exclude[MissingMethodProblem]("psp.std.ImplicitRemoval.psp$std$ImplicitRemoval$_setter_$unaugmentString_=")
[error]  * object psp.std.StringExtensionOps does not have a correspondent in new version
[error]    filter with: ProblemFilters.exclude[MissingClassProblem]("psp.std.StringExtensionOps$")
[error]  * class psp.std.StringExtensionOps does not have a correspondent in new version
[error]    filter with: ProblemFilters.exclude[MissingClassProblem]("psp.std.StringExtensionOps")
java.lang.RuntimeException: psp-std: Binary compatibility check failed!